@hostname = localhost:8080

### Create a new list
# @name create_list
POST http://{{hostname}}/lists HTTP/1.1
Content-Type: application/json

{
  "name": "New List",
  "description": "This is a new list"
}

@list_id = {{ create_list.response.body.id }} 

### GET all lists
# @name get_all_lists
GET http://{{hostname}}/lists HTTP/1.1
Accept: application/json

### GET a list
# @name get_list
GET http://{{hostname}}/lists/{{list_id}} HTTP/1.1
Accept: application/json

### Update a list
PUT http://{{hostname}}/lists/{{list_id}} HTTP/1.1
Content-Type: application/json

{
  "name": "Updated List",
  "description": "This is an updated list"
}

### Create a todo item
# @name create_item
POST http://{{hostname}}/lists/{{list_id}}/items HTTP/1.1
Content-Type: application/json

{
  "name": "New Todo",
  "listId": "{{list_id}}"
}

@item_id = {{ create_item.response.body.id }}

### Delete a todo item
DELETE http://{{hostname}}/lists/{{list_id}}/items/{{item_id}} HTTP/1.1

### GET all todo items
GET http://{{hostname}}/lists/{{list_id}}/items HTTP/1.1

### Get item
GET http://{{hostname}}/lists/{{list_id}}/items/{{item_id}} HTTP/1.1

### Update item state by id
PUT http://{{hostname}}/lists/{{list_id}}/items/{{item_id}} HTTP/1.1
Content-Type: application/json

{
  "state": "INPROGRESS",
  "name": "Updated Todo Item",
  "description": "This is an updated todo item"
}

### Update items state by list id
PUT http://{{hostname}}/lists/0/items/state/DONE HTTP/1.1
Content-Type: application/json

["{{item_id}}"]


### Delete a list
# @name delete_list
DELETE http://{{hostname}}/lists/{{list_id}} HTTP/1.1
